### PR TITLE
Drop Node.js < 6, use ES6.

### PR DESCRIPTION
**Pull request by XhmikosR**
TODO:

- [x] Fix browserify; add babelify
- [x] Fix the remaining lint errors
- [x] See if we can reduce the xo overrides
- [x] Update all deps

@lahmatiy: feel free to push to my branch :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
@lahmatiy: down to 3 errors. Should I keep working on this or drop it?

You can always push to my branch if you want.

**Comment by XhmikosR** [comment]
I added a few more patches. Not sure if I should work on this, I don't see any responses.

**Comment by lahmatiy** [comment]
@XhmikosR Sorry for a long response. I'm on vacation and have no access to my laptop. Will come back in 2 days or so and will sort out PRs and the rest

**Comment by XhmikosR** [comment]
@lahmatiy if I'm going to redo this, will you be able to review it in a timely manner? This branch had a pretty big performance improvement.

BTW do we have a benchmark script?

**Comment by lahmatiy** [comment]
@XhmikosR The changes are huge. I'm ok to update source to use ES6+. However, I don't happy about build and test pipeline changes (please roll back these changes please, it should be discussed first). Some changes are outdates now, e.g. Node.js 8 was dropped in recent 4.0 and browserify was replaced with rollup.

> This branch had a pretty big performance improvement.

How did you realise that? I used [css-minification-benchmark](https://github.com/goalsmashers/css-minification-benchmark/) before, alter it by adding new CSSO version with old one. But I would be happy to have a benchmark in this repo.

**Comment by XhmikosR** [comment]
Well, I need to redo the changes like I said. This patch does not apply
anymore. But the changes will still be a lot hence why a non-ehitespace
diff helps.

I will push a branch tomorrow, but I had some issues with Babel and rollup.
Everything else works fine for me.

As for comparisons you can do another one later, but judging from the CI
tests the difference was big back then. Anyway we'll see how it goes.

**Pull request closed without merging**
